#!/usr/bin/env python3
"""
 Plot a band structure diagram from CSV point sets. See `cp2k-band2csv.py`
 for how to generate the CSVs from CP2K output.

 This script was written by Joseph Wilson under PHYS493, 2019.
 It is free to use and modify.

"""

import argparse
from glob import glob
import numpy as np
import matplotlib as mpl
from matplotlib import pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages


def get_plottable_data(pointsets, labelled_kpoints={}):
    """
    Convert the CSV data from point sets generated by `cp2k-band2csv.py`
    into an easy-to-plot form, complete with special k-point x-labels.

    Returns
    """

    xlabels = {}
    xcoord = 0
    xcoords = []
    data = []
    for pointset in pointsets:
        for kcoord, bandvals in zip(pointset[:, :3], pointset[:, 3:]):

            # find kcoord label
            for labelled_kcoord, label in labelled_kpoints.items():
                # see if kcoord is equal to a labelled kcoord to within floating point precision
                if np.allclose(kcoord, labelled_kcoord):
                    # kcoord is labelled
                    if xcoord in xlabels and xlabels[xcoord] != label:
                        xlabels[xcoord] += '|' + label
                    else:
                        xlabels[xcoord] = label
                    break

            xcoords.append(xcoord)
            data.append(bandvals)

            xcoord += 1
        xcoord -= 1  # have no horizontal gap between point sets

    bands = np.array(data).T
    return bands, xcoords, xlabels


def find_bandgaps(bands):
    """
    Finds the (finite) ranges of energy which contain no bands.
   Uses the fact that the bands are ordered so that their
    successive minima and maxima are non-decreasing.
    """
    gaps = []
    upper = np.inf
    for band in bands:
        lower = band.min()
        if upper < lower:
            gaps.append((upper, lower))
        upper = band.max()
    return gaps


params = {'axes.formatter.limits': [-4, 4],
          'axes.labelsize': 'x-large',
          'xtick.labelsize' : '10',
          'axes.titlesize': 'x-large',
          'legend.fontsize': 'medium',
          'lines.markersize': '8',
          }
plt.rcParams.update(params)
# plt.rcParams['text.usetex'] = True

# User variables
# folder = '/Volumes/ELEMENTS/Storage/Postdoc2/Data/Work/calculations/hfo2/archer/bulk/monoclinic/calculations/band_structure/setyawan-kpoints/yudi-pbe'
# folder = '/Volumes/ELEMENTS/Storage/Postdoc2/Data/Work/calculations/hfo2/archer/bulk/monoclinic/calculations/band_structure/setyawan-kpoints/mp-352-pbe'
# folder = '/Volumes/ELEMENTS/Storage/Postdoc2/Data/Work/calculations/hfo2/archer/bulk/monoclinic/calculations/band_structure/setyawan-kpoints/cell-opt-pbe'
# band_gap_number = -1

# folder = '/Volumes/ELEMENTS/Storage/Postdoc2/Data/Work/calculations/hfo2/archer/bulk/tetragonal/calculations/band_structure/setyawan-kpoints/yudi-pbe'
# folder = '/Volumes/ELEMENTS/Storage/Postdoc2/Data/Work/calculations/hfo2/archer/bulk/tetragonal/calculations/band_structure/setyawan-kpoints/mp-1018721'
# folder = '/Volumes/ELEMENTS/Storage/Postdoc2/Data/Work/calculations/hfo2/archer/bulk/tetragonal/calculations/band_structure/setyawan-kpoints/cell-opt-pbe'
# band_gap_number = -2

folder = '/Volumes/ELEMENTS/Storage/Postdoc2/Data/Work/calculations/hfo2/archer/bulk/po/calculations/band_structure/setyawan-kpoints/yudi-pbe'
folder = '/Volumes/ELEMENTS/Storage/Postdoc2/Data/Work/calculations/hfo2/archer/bulk/po/calculations/band_structure/setyawan-kpoints/mp-685097'
folder = '/Volumes/ELEMENTS/Storage/Postdoc2/Data/Work/calculations/hfo2/archer/bulk/po/calculations/band_structure/setyawan-kpoints/cell-opt-pbe'
band_gap_number = -1

band_file = '{}/bs.band'.format(folder)
plot_ylim = [-5, 9]
plot_ylim = [-6, 7]
plot_ylim = [-2, 6]

pointset_pattern = f'{band_file}.set-*.csv'
pointsets = [np.loadtxt(f) for f in sorted(glob(pointset_pattern))]
kpath_filename = f'{band_file}.kpath.csv'
kpath = np.loadtxt(kpath_filename,
                   dtype=[('label', '<U20'), ('a', float), ('b', float), ('c', float)])
labelled_kpoints = {tuple(kpoint): label for label, *kpoint in kpath}

# convert data
bands, xcoords, xlabels = get_plottable_data(pointsets, labelled_kpoints)
bandgaps = find_bandgaps(bands)

if bandgaps:
    highest_bandgap = bandgaps[band_gap_number]
    print(highest_bandgap)
    print(f"highest bandgap: {highest_bandgap[1] - highest_bandgap[0]:5g} eV")
    yoffset = -highest_bandgap[0]
    print(f"VBM: {highest_bandgap[0] + yoffset :5g} eV")
    print(f"CBM: {highest_bandgap[1] + yoffset :5g} eV")
else:
    print(f"no bandgaps found")
    yoffset = 0

# create figure window and axes
fig, ax = plt.subplots()
sortedxticks = sorted(xlabels.keys())
ax.set_xticks(sortedxticks)
ax.set_xticklabels([xlabels[x] for x in sortedxticks])
for x in sortedxticks:
    ax.axvline(x, c='k', lw=0.5)

# Use default colors
for i, band in enumerate(bands):
    ax.plot(xcoords, band + yoffset)

# Use colormap
# cmap = plt.get_cmap('rainbow', len(bands))
# cmap = plt.get_cmap('hsv')
# for i, band in enumerate(bands):
#     ax.plot(xcoords, band + yoffset, c=cmap(i))

# Use pre-defined colors
# plotting_colors = ['r', 'g', 'b', 'm', 'grey', 'orange', 'y', 'brown', 'cyan'] * 10
# for i, band in enumerate(bands):
#     ax.plot(xcoords, band + yoffset, c=plotting_colors[i])

# shade in the bandgap region
for lower, upper in bandgaps:
    ax.axhspan(lower + yoffset, upper + yoffset, alpha=0.2)

ax.set_ylabel(r'E - E$_\mathrm{f}$ (eV)')
# ax.set_xlabel("$k$")
ax.set_ylim([plot_ylim[0], plot_ylim[1]])

ax.autoscale(tight=True, axis='x')
plt.tight_layout()
plt.savefig('{}/band_structure.png'.format(folder), dpi=600)
plt.show()
